export interface AppPermissions {
  canViewDashboard: boolean;
  canViewAll: boolean;
  canCreateTraining: boolean;
  canEditTraining: boolean;
  canDeleteTraining: boolean;
  canUploadParticipants: boolean;
  canAssignTrainer: boolean;
  canEditAttendance: boolean;
  canConfirmHigh: boolean;
  canDeleteHighs?: boolean;
  canApproveReopen: boolean;
  canManageUsers: boolean;
  canDeleteUsers?: boolean;
  canCreateSurvey?: boolean;
  canDeleteSurvey?: boolean;
  canExportReports: boolean;
  canReopenClosedTraining?: boolean;
  canCloseTraining?: boolean;
  canViewHighsReadOnly?: boolean;
  readOnly?: boolean;
}

export const permissions: Record<string, AppPermissions> = {
  Administrador: {
    canViewDashboard: true,
    canViewAll: true,
    canCreateTraining: true,
    canEditTraining: true,
    canDeleteTraining: true,
    canUploadParticipants: true,
    canAssignTrainer: true,
    canEditAttendance: true,
    canConfirmHigh: true,
    canDeleteHighs: true,
    canApproveReopen: true,
    canManageUsers: true,
    canDeleteUsers: true,
    canCreateSurvey: true,
    canDeleteSurvey: true,
    canExportReports: true,
    canReopenClosedTraining: true,
    canCloseTraining: true,
    readOnly: false,
  },
  Analista: {
    canViewDashboard: true,
    canViewAll: true,
    canCreateTraining: true,
    canEditTraining: true,
    canDeleteTraining: false,
    canUploadParticipants: true,
    canAssignTrainer: true,
    canEditAttendance: false,
    canConfirmHigh: false,
    canDeleteHighs: false,
    canApproveReopen: false,
    canManageUsers: false,
    canDeleteUsers: false,
    canCreateSurvey: true,
    canDeleteSurvey: false,
    canExportReports: true,
    canReopenClosedTraining: true,
    canCloseTraining: false,
    readOnly: false,
  },
  Reclutador: {
    canViewDashboard: false,
    canViewAll: false,
    canCreateTraining: true,
    canEditTraining: true,
    canDeleteTraining: false,
    canUploadParticipants: true,
    canAssignTrainer: true,
    canEditAttendance: false,
    canConfirmHigh: true,
    canApproveReopen: false,
    canManageUsers: false,
    canDeleteUsers: false,
    canCreateSurvey: true,
    canDeleteSurvey: false,
    canExportReports: false,
    canReopenClosedTraining: false,
    canCloseTraining: false,
    canViewHighsReadOnly: true,
    readOnly: false,
  },
  Formador: {
    canViewDashboard: false,
    canViewAll: false,
    canCreateTraining: false,
    canEditTraining: false,
    canDeleteTraining: false,
    canUploadParticipants: false,
    canAssignTrainer: false,
    canEditAttendance: true,
    canConfirmHigh: true,
    canApproveReopen: false,
    canManageUsers: false,
    canDeleteUsers: false,
    canExportReports: false,
    canReopenClosedTraining: false,
    canCloseTraining: true,
    readOnly: false,
  },
  Coordinador: {
    canViewDashboard: true,
    canViewAll: false,
    canCreateTraining: true,
    canEditTraining: true,
    canDeleteTraining: false,
    canUploadParticipants: true,
    canAssignTrainer: true,
    canEditAttendance: false,
    canConfirmHigh: true,
    canApproveReopen: false,
    canManageUsers: false,
    canDeleteUsers: false,
    canCreateSurvey: true,
    canDeleteSurvey: false,
    canExportReports: true,
    canReopenClosedTraining: false,
    canCloseTraining: false,
    canViewHighsReadOnly: false,
    readOnly: false,
  },
  Sistemas: {
    canViewDashboard: true,
    canViewAll: true,
    canCreateTraining: false,
    canEditTraining: false,
    canDeleteTraining: false,
    canUploadParticipants: false,
    canAssignTrainer: false,
    canEditAttendance: false,
    canConfirmHigh: false,
    canApproveReopen: false,
    canManageUsers: false,
    canDeleteUsers: false,
    canExportReports: true,
    canReopenClosedTraining: false,
    canCloseTraining: false,
    readOnly: true,
  },
};
